# Generated by Django 3.1.7 on 2021-04-15 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('poster', models.ImageField(null=True, upload_to='DeveloperPoster/', verbose_name='Постер')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('release', models.DateField(verbose_name='Дата релиза')),
                ('poster', models.ImageField(null=True, upload_to='gamePoster/', verbose_name='Постер')),
                ('count_download', models.IntegerField(verbose_name='Количество скачиваний')),
                ('demandsOS', models.CharField(blank=True, max_length=150, verbose_name='ОС')),
                ('demandsCPU', models.CharField(blank=True, max_length=150, verbose_name='Процессор')),
                ('demandsRAM', models.CharField(blank=True, max_length=150, verbose_name='Оперативная память')),
                ('demandsGPU', models.CharField(blank=True, max_length=150, verbose_name='Видеокарта')),
                ('demandsROM', models.CharField(blank=True, max_length=150, verbose_name='Место на диске')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('developer', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='gameApp.developer', verbose_name='Разработчик')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Метка')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('poster', models.ImageField(null=True, upload_to='PublisherPoster/', verbose_name='Постер')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameApp.game')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameApp.gamelabel')),
            ],
            options={
                'verbose_name': 'Метка к игре',
                'verbose_name_plural': 'Метки к играм',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('star', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameApp.game', verbose_name='Игра')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameApp.reviews', verbose_name='Родитель')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='GameShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('image', models.ImageField(null=True, upload_to='GameShots/', verbose_name='Изображение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameApp.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='gameApp.publisher', verbose_name='Издатель'),
        ),
    ]
