# Generated by Django 3.1.7 on 2021-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='DeveloperPoster/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='PublisherPoster/', verbose_name='Постер'),
        ),
    ]
