# Generated by Django 3.1.7 on 2021-03-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('poster', models.ImageField(null=True, upload_to='DeveloperPoster/', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('poster', models.ImageField(null=True, upload_to='PublisherPoster/', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.AlterModelOptions(
            name='tagged',
            options={'verbose_name': 'Метка к игре', 'verbose_name_plural': 'Метки к играм'},
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='gameApp.developer', verbose_name='Разработчик'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='gameApp.publisher', verbose_name='Издатель'),
        ),
    ]
