# Generated by Django 3.1.7 on 2021-06-08 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameApp', '0005_gamelibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.CreateModel(
            name='HistoryPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePay', models.DateTimeField(verbose_name='Дата покупки')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameApp.game', verbose_name='Корзина')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
