# Generated by Django 3.1.7 on 2021-06-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0006_auto_20210608_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypay',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameApp.cart', verbose_name='Корзина'),
        ),
    ]
