# Generated by Django 3.1.7 on 2021-06-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0007_auto_20210608_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historypay',
            options={'verbose_name': 'Библиотека', 'verbose_name_plural': 'Библиотеки'},
        ),
    ]
