# Generated by Django 3.1.7 on 2021-06-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0008_auto_20210608_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historypay',
            options={'verbose_name': 'История покупок', 'verbose_name_plural': 'Истории покупок'},
        ),
        migrations.AlterField(
            model_name='historypay',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gameApp.cart', verbose_name='Корзина'),
        ),
    ]
