# Generated by Django 3.1.7 on 2021-06-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0009_auto_20210609_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypay',
            name='cart',
        ),
        migrations.AddField(
            model_name='historypay',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gameApp.game', verbose_name='Игра'),
        ),
    ]
