# Generated by Django 3.1.7 on 2021-05-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_auto_20210523_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='m_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_to', to='userApp.friends', verbose_name='Друг'),
        ),
    ]
